version: '3'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DATABASE_HOST: db
    restart: always
    ports:
      - "3306:3306"
  web:
    build: ./web
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DATABASE_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always